const ChatBotData = {
    "How do I register for an account": "To register, click on the 'Sign Up' button on the homepage and fill in your details. Once you've completed the form, you'll receive a confirmation email. Follow the instructions in the email to activate your account.",
    "I'm having troubles logging in to the app": "Click on the 'Log In' button at the top right corner of the page. Enter your email and password, then click 'Submit' to access your account.",
    "How do I recover my password": "No worries! Just click on the 'Forgot Password?' link on the login page, and I'll help you reset it. You'll receive an email with instructions on how to create a new password.",
    "How to browse the menu": "You can browse the menu by visiting the 'Menu' section. You'll see a list of available meals and categories. Use the filters to find what you're looking for.",
    "How to filter meals by dietary restrictions": "Yes, you can! Use the filters in the 'Menu' section to select options like vegetarian, vegan, gluten-free, or other dietary preferences.",
    "How to place an order in the app": "To place an order, browse through the menu, select the items you want, and add them to your cart. Once you're ready, click on the cart icon to review your order and proceed to checkout.",
    "Is there a way I can view past orders": "Yes, you can view your past orders in the 'Order History' section of your account. You'll find a list of all previous orders with details like date, items ordered, and total cost.",
    "Do you offer payment options": "We offer several payment options, including credit/debit cards, mobile payment options, and cash on delivery. Choose the one that suits you best at checkout.",
    "How is your delivery fee like": "Delivery fees may apply depending on your location and the total amount of your order. You can see the delivery fee before you confirm your order at checkout.",
    "How to schedule a delivery": "Absolutely! When placing your order, select the option to schedule delivery and choose your preferred time slot. We'll deliver your food right on time.",
    "How do I update delivery address": "You can update your delivery address in the 'Account Settings' section. Click on 'Edit Address,' make your changes, and save them.",
    "How can I cancel my order": "If you need to cancel your order, go to the 'Order History' section and select the order you want to cancel. Click on the 'Cancel Order' button, and we'll take care of it.",
    "How to customize my order": "Yes, many of our menu items can be customized. When you select a meal, look for customization options like toppings, sides, and more.",
    "opening hours": "Our canteen operates from 8:00 AM to 8:00 PM, Monday through Friday. Weekend hours may vary, so please check the 'Hours' section for up-to-date information.",
    "How to contact customer support": "You can contact our customer support team through the 'Help' section. Choose the 'Contact Us' option and fill in the form, or use the live chat feature.",
    "How do leave a review": "We'd love to hear your feedback! You can leave a review by going to the 'Order History' section, selecting the meal you want to review, and clicking on the 'Leave a Review' button.",
    "How to see meal ratings": "Yes, meal ratings are displayed in the 'Menu' section. You can see the average rating and read reviews from other students to help you decide.",
    "Do you offer student discounts": "We do offer discounts and promotions from time to time. Check the 'Offers' section or sign up for our newsletter to stay updated on the latest deals.",
    "Is there any special offers today": "Let me check... Yes, we have a special offer today! You can get a 10% discount on all orders above $20. Use the code 'SAVE10' at checkout.",
    "I want to update payment information": "You can update your payment information in the 'Account Settings' section. Click on 'Payment Methods,' make your changes, and save them.",
    "Can I order from multiple vendors": "Currently, you can only order from one vendor at a time. If you want to order from multiple vendors, please place separate orders.",
    "How to track my order": "You can track your order in real-time by going to the 'Order Status' section. You'll see updates on the preparation and delivery progress.",
    "The steps in seeing order confirmation": "Once your order is confirmed, you'll receive a confirmation email and a notification in the app. You can also check the 'Order Status' section for updates.",
    "I would like to change my order": "If your order hasn't been prepared yet, you might be able to make changes. Please go to 'Order History' and select the order you want to modify. If changes are allowed, you'll see an 'Edit Order' option.",
    "How do I become a vendor": "We're always looking for great vendors! If you're interested, please go to the 'Become a Vendor' section and fill out the application form. Our team will review it and get back to you.",
    "My food is late": "I'm sorry for the delay! Please check the 'Order Status' section for updates. If your food is still late, you can contact our support team through the 'Help' section.",
    "Is there any minimum order amount": "Some vendors may have a minimum order amount. You'll see this information in the 'Menu' section when selecting your items.",
    "Do you constantly update your menu items": "We regularly update our menu with new items. Keep an eye on the 'New Arrivals' section, and sign up for our newsletter to get the latest updates.",
    "How to save favorite meals": "Yes, you can save your favorite meals by clicking the heart icon next to the item. You can view your favorites in the 'Favorites' section of your account.",
    "I'm allergic to some ingredients": "Your safety is important to us. Please check the ingredient list provided for each meal. You can also use filters to exclude meals with allergens. If you're unsure, contact the vendor for more information.",
    "give app feedback": "We value your feedback! You can provide feedback through the 'Feedback' section in the app or contact our support team directly.",
    "I received a wrong order": "I apologize for the inconvenience. Please go to the 'Order History' section, select the incorrect order, and click on 'Report an Issue.' Our support team will assist you.",
    "How do I order drinks": "Yes, you can order drinks! Look for the 'Drinks' category in the menu to see the available options.",
    "How do you choose trustworthy vendors": "We carefully vet all our vendors to ensure quality and reliability. You can also check vendor ratings and reviews from other students to make an informed decision.",
    "My app not working": "If you're experiencing issues with the app, try restarting it or checking your internet connection. If the problem persists, please contact our support team through the 'Help' section.",
    "Can I share order with friends": "Currently, sharing an order directly through the app isn't supported. However, you can share your favorite meals with friends and encourage them to order!",
    "I would like to suggest menu items": "We'd love to hear your ideas! Please use the 'Feedback' section to suggest new menu items, and we'll pass them on to our vendors.",
    "How do contact vendor directly": "Currently, direct communication with vendors through the app is not supported. If you have specific questions, please contact our support team, and we will assist you.",
    "How to log out": "To log out, go to the 'Account' section and click on the 'Log Out' button. You'll be logged out of your account immediately.",
    "How do I change my email address": "Yes, you can change your email address in the 'Account Settings' section. Click on 'Edit Email,' enter your new email address, and save the changes.",
    "I have accidentally logged out": "If you log out by accident, don't worry! You can log back in using your email and password. If you've forgotten your password, use the 'Forgot Password?' link to reset it.",
    "I want to delete my account": "We're sorry to see you go! If you wish to delete your account, please go to the 'Account Settings' section, select 'Delete Account,' and follow the instructions.",
    "My payment declined": "If your payment method is declined, please check your card details and try again. You can also add a new payment method or contact your bank for assistance.",
    "Can I have multiple payment methods": "Currently, you can only use one payment method per order. If you need to use a different method, please update your payment information before placing the order.",
    "What is your privacy standard": "Yes, your privacy is important to us. We use industry-standard encryption and security measures to protect your personal information.",
    "Can I Contrubute to the app improvement suggestions": "We appreciate your suggestions! Please use the 'Feedback' section to share your thoughts on how we can improve the app. We're always looking for ways to serve you better.",
    "Hello I'm fred": "Hello fred how may I assist you.",
    "Hello I'm Juan": "Nice to meet you Juan How may I be of help."
};

export default ChatBotData;
